apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bluecrypt47/argocd-test.git
    targetRevision: master
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: static-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

