apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd  # Namespace của ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/user/my-app.git  # Repo chứa Kubernetes manifests
    targetRevision: main  # Branch/tag cần deploy
    path: k8s-manifests  # Thư mục chứa manifests
  destination:
    server: https://kubernetes.default.svc  # Cụm K8s đích
    namespace: my-app  # Namespace để deploy app
  syncPolicy:
    automated:
      prune: true  # Xóa resource không còn trong Git
      selfHeal: true  # Tự động sửa lỗi khi khác Git
    syncOptions:
      - CreateNamespace=true  # Tự động tạo namespace nếu chưa có
