name: Deploy Static Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug - Kiểm tra thư mục hiện tại
        run: pwd && ls -la

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t chuongle1/static-site:$IMAGE_TAG -f DOCKERFILE .
          docker push chuongle1/static-site:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Kubernetes manifest
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          sed -i "s|image: chuongle1/static-site:.*|image: chuongle1/static-site:${{ env.IMAGE_TAG }}|" k8s-manifests/deployment.yaml
          git add k8s-manifests/deployment.yaml
          git commit -m "Update image to version ${{ env.IMAGE_TAG }}"
          git push origin main
